### ISSUE TITLE
缺少这个文件LV-MHP-v2_colormap.mat

### ISSUE THREAD

**Issue by yatoubusha** [cjm-sfw/Uniparser#3]
麻烦作者能提供下这个文件吗？或者去哪里可以下载？是在数据集里包含的吗？数据集里有5G，好大，能否单独分享下这个文件？超级感谢

**Comment by cjm-sfw** [comment]
https://drive.google.com/file/d/1CmmcazMugB2DLUb-LEe-3ESEcxzFikGd/view?usp=sharing

**Comment by yatoubusha** [comment]
> https://drive.google.com/file/d/1CmmcazMugB2DLUb-LEe-3ESEcxzFikGd/view?usp=sharing

thanks a lot!
