### ISSUE TITLE
Can you please update license of this Github repository?

### ISSUE THREAD

**Issue by sanchit88** [cjm-sfw/Uniparser#4]
Hi Authors,
     First of all, congrats to your great work. I would like to try and test out your model, however, I see that the license of this Github repo is not updated. Therefore, can you please update the license like `MIT` or `Apache 2.0` such that other people can test out your model. Thanks a lot!

**Comment by cjm-sfw** [comment]
Our code is based on the framework MMdetection which is released under the [Apache 2.0 license](https://github.com/open-mmlab/mmdetection/blob/main/LICENSE). So I think you could test our model as it's under Apache 2.0 license.
